# a=[]
# a1=input("Enter the fruit name!")
# a.append(a1)
# a1=input("Enter the fruit name!")
# a.append(a1)
# a1=input("Enter the fruit name!")
# a.append(a1)
# a1=input("Enter the fruit name!")
# a.append(a1)
# a1=input("Enter the fruit name!")
# a.append(a1)
# a1=input("Enter the fruit name!")
# a.append(a1)
# a1=input("Enter the fruit name!")
# a.append(a1)
# print(a)

# a=[]
# a1=int(input("Enter the marks name!"))
# a.append(a1)
# a1=int(input("Enter the marks name!"))
# a.append(a1)
# a1=int(input("Enter the marks name!"))
# a.append(a1)
# a1=int(input("Enter the marks name!"))
# a.append(a1)
# a1=int(input("Enter the marks name!"))
# a.append(a1)
# a1=int(input("Enter the marks name!"))
# a.append(a1)
# a1=int(input("Enter the marks name!"))
# a.append(a1)
# print(a)
# a.sort()
# print(a)

# a=[]
# a1=int(input("Enter the number! "))
# a.append(a1)
# a1=int(input("Enter the number! "))
# a.append(a1)
# a1=int(input("Enter the number! "))
# a.append(a1)
# a1=int(input("Enter the number! "))
# a.append(a1)
# print(a[0]+a[1]+a[2]+a[3])

# a=(7,0,8,0,0,9)
# print(a.count(0))